version: '2'
services:
  hub:
    image: dosel/zalenium
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/videos:/home/seluser/videos
    ports:
      - "4444:4444"
    command: >
      start --desiredContainers 0

  bulletin:
    image: bulletin_board:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"

  ruby_test:
    image: ruby_test:latest
    build:
      context: ./grid
      dockerfile: ./Dockerfile
    depends_on:
      - hub
      - bulletin
